name: Deploy
on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: "prod"
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "23.x"

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build
        env:
          NEXT_PUBLIC_SITE_URL: ${{vars.NEXT_PUBLIC_SITE_URL}}
          NEXT_PUBLIC_API_URL: ${{vars.NEXT_PUBLIC_API_URL}}

      - name: Deploy to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{vars.HOST}}
          username: "ubuntu"
          key: ${{secrets.KEY}}
          port: 22
          source: "./.next/standalone"
          target: "/var/www/crosspace/client"
          overwrite: true
          strip_components: 3

      - name: Restart the server
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{vars.HOST}}
          username: "ubuntu"
          key: ${{secrets.KEY}}
          port: 22
          script: |
            sudo docker compose -f /var/www/crosspace/docker-compose.yml restart client
            sudo docker compose -f /var/www/crosspace/docker-compose.yml restart nginx
